package com.urlshortener.controller;

import com.urlshortener.dto.UrlDto.*;
import com.urlshortener.service.UrlService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/urls")
@RequiredArgsConstructor
public class UrlController {

    //injected by Spring via the constructor generated by @RequiredArgsConstructor
    private final UrlService urlService;

    //Creating a new shortened URL.
    @PostMapping
    public ResponseEntity<ApiResponse<UrlResponse>> createShortUrl(
            @Valid @RequestBody CreateUrlRequest request) {
        UrlResponse urlResponse = urlService.createShortUrl(request);

        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(ApiResponse.success("Yo! Short URL created successfully!", urlResponse));
    }

    //returns full details of a URL by its short code,not a redirect just returns information.
    @GetMapping("/{shortCode}")
    public ResponseEntity<ApiResponse<UrlResponse>> getUrl(@PathVariable String shortCode) {

        UrlResponse urlResponse = urlService.getUrlByShortCode(shortCode);

        return ResponseEntity.ok(
                ApiResponse.success("URL details retrieved successfully!!!", urlResponse));
    }

    //Returns all active URLs ordered by newest first.
    @GetMapping
    public ResponseEntity<ApiResponse<List<UrlResponse>>> getAllUrls() {
        List<UrlResponse> urls = urlService.getAllUrls();

        return ResponseEntity.ok(
                ApiResponse.success("Retrieved " + urls.size() + " URLs", urls));
    }

    //for returning the top 10 most clicked URLs.
    @GetMapping("/top/popular")
    public ResponseEntity<ApiResponse<List<UrlResponse>>> getTopUrls() {

        List<UrlResponse> topUrls = urlService.getTopUrls();
        return ResponseEntity.ok(
                ApiResponse.success("Top " + topUrls.size() + " most clicked URLs", topUrls));
    }

    //this returns analytics for a specific short URL.
    @GetMapping("/{shortCode}/stats")
    public ResponseEntity<ApiResponse<UrlStatsResponse>> getUrlStats(@PathVariable String shortCode) {
        UrlStatsResponse stats = urlService.getUrlStats(shortCode);
        return ResponseEntity.ok(
                ApiResponse.success("URL stats retrieved", stats));
    }

    //for updating an existing URL's destination or active status.
    @PutMapping("/{shortCode}")
    public ResponseEntity<ApiResponse<UrlResponse>> updateUrl(
            @PathVariable String shortCode,
            @Valid @RequestBody UpdateUrlRequest request) {

        UrlResponse updatedUrl = urlService.updateUrl(shortCode, request);
        return ResponseEntity.ok(
                ApiResponse.success("URL updated successfully!!!!", updatedUrl));
    }

    //deleting a URL.
    @DeleteMapping("/{shortCode}")
    public ResponseEntity<ApiResponse<String>> deleteUrl(@PathVariable String shortCode) {

        urlService.deleteUrl(shortCode);
        return ResponseEntity.ok(
                ApiResponse.success("URL deleted successfully", "Deleted : " + shortCode));
    }
}
