spring.application.name=url-shortener

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# The JDBC driver class for PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Tell Hibernate which database dialect (language variation) to use.
# Different databases have slightly different SQL syntax.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# When redirecting, we'll generate links like: http://localhost:8080/s/abc123
app.base-url=http://localhost:8080

# ex: length=6 generates codes like: abc123, xK9pL2
app.short-code-length=6

#   Logging
logging.level.com.urlshortener=DEBUG

# Log level for Hibernate SQL binding parameters (shows actual values in queries)
logging.level.org.hibernate.type.descriptor.sql=TRACE
